export const industryPresets = {
  general: {
    offerTitle: 'Free consultation',
    offerBullets: ['We confirm your details', 'We contact you shortly', 'You get a clear next step'],
    defaultWhatsappTemplate: "Hi {name}, thanks for your request. I see you’re in {suburb}. When can we call you today?",
    budgetLabel: 'Budget range',
    budgetOptions: ['Not sure', 'Low', 'Medium', 'High'],
    timelineLabel: 'When do you want this?',
    timelineOptions: ['ASAP', '1–3 months', 'Just checking'],
    serviceTypeEnabled: false,
    serviceTypeLabel: 'What do you need help with?',
    serviceTypeOptions: [],
  },
  solar: {
    offerTitle: 'Free solar assessment',
    offerBullets: ['We confirm your details', 'We schedule a quick call', 'You get a tailored solar quote'],
    defaultWhatsappTemplate: "Hi {name}, thanks for requesting a free solar assessment. I see you’re in {suburb}. When can we call you today?",
    budgetLabel: 'Monthly electricity bill',
    budgetOptions: ['R0–R1,500', 'R1,500–R3,000', 'R3,000–R5,000', 'R5,000+', 'Not sure'],
    timelineLabel: 'Timeline',
    timelineOptions: ['ASAP', '1–3 months', 'Just checking'],
    serviceTypeEnabled: false,
    serviceTypeLabel: 'What do you need help with?',
    serviceTypeOptions: [],
  },
  law: {
    offerTitle: 'Free case review',
    offerBullets: ['We confirm your details', 'A lawyer reviews your matter', 'We advise the best next step'],
    defaultWhatsappTemplate: "Hi {name}, thanks for reaching out. I see you’re in {suburb}. What type of matter is this ({serviceType}) and when can we call you?",
    budgetLabel: 'Matter value / Budget range',
    budgetOptions: ['Not sure', 'Under R10k', 'R10k–R50k', 'R50k+'],
    timelineLabel: 'When do you need help?',
    timelineOptions: ['ASAP', 'This week', 'Just checking'],
    serviceTypeEnabled: true,
    serviceTypeLabel: 'What do you need help with?',
    serviceTypeOptions: ['Family law', 'Criminal defence', 'Labour / employment', 'Property / conveyancing', 'Other'],
  },
  plumbing: {
    offerTitle: 'Free call-out estimate',
    offerBullets: ['We confirm your details', 'A plumber calls to diagnose', 'We book the soonest slot'],
    defaultWhatsappTemplate: "Hi {name}, thanks for your request. I see you’re in {suburb}. What do you need help with ({serviceType}) and when can we come out?",
    budgetLabel: 'Budget range',
    budgetOptions: ['Not sure', 'Under R1k', 'R1k–R3k', 'R3k+'],
    timelineLabel: 'Urgency',
    timelineOptions: ['ASAP', 'This week', 'Just checking'],
    serviceTypeEnabled: true,
    serviceTypeLabel: 'Service type',
    serviceTypeOptions: ['Leak / burst pipe', 'Blocked drain', 'Geyser', 'New installation', 'Other'],
  },
  dentist: {
    offerTitle: 'Free booking assist',
    offerBullets: ['We confirm your details', 'We contact you shortly', 'We help you book the right slot'],
    defaultWhatsappTemplate: "Hi {name}, thanks for your request. I see you’re in {suburb}. What do you need help with ({serviceType}) and when would you like an appointment?",
    budgetLabel: 'Budget range',
    budgetOptions: ['Not sure', 'Under R1k', 'R1k–R3k', 'R3k+'],
    timelineLabel: 'When do you want this?',
    timelineOptions: ['ASAP', 'This week', 'Just checking'],
    serviceTypeEnabled: true,
    serviceTypeLabel: 'Service type',
    serviceTypeOptions: ['Check-up', 'Toothache', 'Cleaning', 'Whitening', 'Other'],
  },
} as const;

export type IndustryPresetKey = keyof typeof industryPresets;
